# Instructions:

You have to submit the Notebook before the deadline:

*   Before you start go to the menu in the upper left corner and click file->Save a copy in Drive.
*   Modify (add your name) the notebook name to **firstname_lastname_NumPy_Assignment.ipynb**.

In [1]:
import numpy as np

# Exercise 1:

1. Create 3 arrays $X$, $w$ and $y$ with shapes (3,4), (2,1) and (6,1) respectively such that:

  * $X$ is a sample from the standard normal distribution
  * $w$ an $y$ are filled  with random floats

2. Perform the following operations:

  * Find the minimum value in $X$.
  * Find the maximum value in each row of $X$.
  * Reshape $X$ such that, the operation $Xw$  will result in an array of a shape (6,1).
  * Find the L2 norm  $||Xw-y||^2$.

In [43]:
## WRITE YOUR CODE HERE ##

#np.random.normal?

X = np.random.normal(size=(3,4))
w = np.random.random(size=(2,1))
y = np.random.random(size=(6,1))
print('X_shape', X.shape , '\nX =', X)
print('w_shape', w.shape, '\nw =  ', w)
print('y_shape', y.shape, '\n y=', y)
print('The minimun and the maximun of each row values in X are respectively ', np.min(X), np.max(X, axis = 1) )
# Reshape X in (6,2)
X_reshape = X.reshape(6,2) 
Xw = X_reshape @ w
#Let find the L2
l_2_norm = sum((X_reshape@w - y)**2) # using the formula
l2_norm_squared = np.linalg.norm(Xw - y) ** 2 #using the built in fonction
print('The L2 norm is equal to  ', l_2_norm, l2_norm_squared )

X_shape (3, 4) 
X = [[ 0.73419327  0.30167396  0.12149068 -0.60344194]
 [ 0.24787272 -1.21032819  1.64795865  0.24571978]
 [-0.14984459 -0.41306235 -0.57090805  1.67287578]]
w_shape (2, 1) 
w =   [[0.68834716]
 [0.91184372]]
y_shape (6, 1) 
 y= [[0.458586  ]
 [0.14726089]
 [0.25974128]
 [0.09670787]
 [0.35707881]
 [0.05846017]]
The minimun and the maximun of each row values in X are respectively  -1.210328188482563 [0.73419327 1.64795865 1.67287578]
The L2 norm is equal to   [5.34877167] 5.348771667935


# Exercise 2

Replace all values greater than or equal to 0.5 with 1, else remain the same.


In [55]:
a = np.array([0, 0.6, 0.5, 0, 0, 0.9, 1, 0,0,0.8])

b = np.where( a >= 0.5, 1, a)
b

array([0., 1., 1., 0., 0., 1., 1., 0., 0., 1.])

# Exercise 3:

Create a (4X4) array with 1 on the border and 0 inside

In [68]:
## WRITE YOUR CODE HERE ##

a = np.ones((4,4), dtype = int)
print(a)
a[1:-1,1:-1]=0
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


# Exercise 4:

Remove all rows with nan values in the given array.

Hint: use `np.isnan()`

Expected output:

        array([[37.5, 24.1,  2.2],
               [18.1,  4.8, 32. ]])

In [81]:
a = np.array([[37.5, 24.1, 2.2],
             [25.4, np.nan, 38],
             [18.1, 4.8, 32],
             [np.nan, np.nan, 28.9]
                ])
b = a[np.isnan(a).sum(axis=1) == 0] 
b

array([[37.5, 24.1,  2.2],
       [18.1,  4.8, 32. ]])

# Exercice 5
Sort the following NumPy array:
 - by the 2nd row. Expected output:

        array([
              [ 6, 45, 34],
              [16, 21, 67],
              [32, 40, 17]])
 - by the 2nd column. Expected output:

       array([[45,  6, 34],
              [21, 16, 67],
              [40, 32, 17]])

In [92]:
a = np.array([[45,6,34],[21,16,67],[40,32,17]])

print(a[:, a[1].argsort()])

print(a[a[:,1].argsort()])


[[ 6 45 34]
 [16 21 67]
 [32 40 17]]
[[45  6 34]
 [21 16 67]
 [40 32 17]]


# Exercise 6:

## Problem Description:

In this exercise, you are required to implement a function that performs Principal Component Analysis (PCA) on a given array of dataset using Singular Value Decomposition (SVD).


### Instructions:

A. Write a function named **pca_with_svd()** that takes a 2D array X as input, where each row represents a data point and each column represents a feature.

Inside the function:

1. Center X by substracting the column-mean from each column.
2. Decompose the centered X using SVD (`np.linalg.svd()`) to obtain the matrices $U$, $Σ$, $V^T$

  where:
    * $U$ is a 2D array containing the eigenvectors as columns.
    * $Σ$ is a 1D array containing the singular values.

3. Extract the principal components (PCs).

  Hint: $PCs = V^T$

4. The function should return a tuple of  $X\_centered$, $PCs$, $U$ and $Σ$


B. Write a second function named  **get_projected_data()** that:

1. Project the array X onto the subspace defined by the $V$.

  **Hint**:  $projected\_X = XV = US$ where, S is the 2D diagonal matrix of singular values.
2. Return a 2D array representing the projected data.



In [93]:
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [97]:
##  COMPLETE THE CODE ##

def pca_with_svd(X):

    # Step 1: Compute the mean-centered X matrix
    mean_centered = X - np.mean(X, axis = 0)

    # Step 2: Use SVD to obtain U, Sigma, and V^T

    U, sigma, VT = np.linalg.svd(mean_centered, full_matrices= False)

    # Step 3: Extract the principal components from V
    pcs = VT

    # Step 4: Return the result as a tuple

    return mean_centered, pcs, U, sigma

def get_projected_data(U, S):

    S_matrix = np.diag(S)

    # Project the data onto the subspace defined by V
    projected_X = np.dot(U, S_matrix)

    # Return the projected data
    return projected_X


In [98]:
X_centered,principal_components,U, singular_values = pca_with_svd(X)

projected_data = get_projected_data(U, singular_values)

# Display the results
print("\nPrincipal Components:\n", principal_components)
print("\nSingular Values:", singular_values)
print("\nProjected Data:\n", projected_data)


Principal Components:
 [[ 0.57735027  0.57735027  0.57735027]
 [-0.81649658  0.40824829  0.40824829]
 [ 0.         -0.70710678  0.70710678]]

Singular Values: [7.34846923e+00 5.12445350e-16 9.25702808e-48]

Projected Data:
 [[-5.19615242e+00  3.62353582e-16  1.45343900e-63]
 [ 0.00000000e+00  0.00000000e+00  9.25702808e-48]
 [ 5.19615242e+00  3.62353582e-16  1.45343900e-63]]
